### ISSUE TITLE
uri is a static entry pointing to 'http://splunk.bluefactory.nl:8088/services/collector/event'

### ISSUE THREAD

**Issue by dannyk81** [cmeerbeek/fluent-plugin-splunkhec#1]
Hey,

Been trying to use your plugin for few hours now and couldn't figure out why I keep getting 
`[debug]: plugin/out_splunkhec.rb:79:block in write: splunkhec: response HTTP Status Code is 403` 
although nothing is received on Splunk server (monitoring port 8088 using tcpdump).

I looked at your code and found that you define the `uri` with a static URL instead of using the constructed `@splunk_url`

so, I guess line 63 should be:
          `uri = URI(@splunk_url)`
instead of:
          `uri = URI('http://splunk.bluefactory.nl:8088/services/collector/event')`

**Comment by dannyk81** [comment]
Tested it and it works, PR #2 submitted

**Comment by cmeerbeek** [comment]
Hi Danny,
Thanks for pointing this out. Don't know why this got into the commit from my side.
I've merged the request.
