### ISSUE TITLE
Allow dynamic indexes, token and sourcetypes

### ISSUE THREAD

**Issue by rmacian** [cmeerbeek/fluent-plugin-splunkhec#19]
As I wanted to be capable of setting different indexes, token and sourcetypes per pod I modified the plugin so it can read the kubernetes tags from the pods and the plugin to read dinamically those variables.

https://github.com/rmacian/fluent-plugin-splunkhec/commit/29b5c94f7cd5188a22b1fe50404f71d43f615711

**Comment by cmeerbeek** [comment]
Hi @rmacian. No experience with kubernetes here. Does this fork mean it will only work with kubernetes or also outside of kubernetes?

**Comment by juzsal** [comment]
This is actually really cool, I was looking for something like this. It doesn't mean it will only work with kubernetes, it just means that the sourcetypes etc. can be worked out dynamically based on the incoming record. Would love to see this merged as a PR!

**Comment by cmeerbeek** [comment]
Version 1.9 is now pushed to GitHub with those changes. Need some people who can test it...
