### ISSUE TITLE
error via td-agent

### ISSUE THREAD

**Issue by saranya2612** [cmeerbeek/fluent-plugin-splunkhec#4]
<source>
  @type tail

  path /opt/as/apps/fluewaasd1/logs/fluewaasd1-tcs1/tomcat.log

  tag tomcat.log

  format none

  refresh_interval 60

</source>

<match tomcat.log>

    @type splunkhec

    host splunk_host

    port 8080

    token C2DF0472-5022

    index main

    event_host fluent_host

    source http:fluentd

</match>

Im getting below error. The tag matches and not sure what this error indicates.

/etc/init.d/td-agent reload
2017-05-26 02:36:17 -0400 [error]: config error file="/etc/td-agent/td-agent.conf" error="Unknown output plugin 'splunkhec'. Run 'gem search -rd fluent-plugin' to find plugins"

**Comment by cmeerbeek** [comment]
Hi Saranya,

Are you sure you installed the plugin? TD-agent can't find it.
Can you show me the output of "sudo td-agent-gem list"?

**Comment by cmeerbeek** [comment]
Didn't get any response so I am going to close this. Feel free to open another issue if needed.
