### ISSUE TITLE
event_sourcetype fails to match correct tag

### ISSUE THREAD

**Issue by wimnat** [cmeerbeek/fluent-plugin-splunkhec#8]
Due to the way event_sourcetype is scoped, the incorrect sourcetype can show up in scope.

I was sending all of my linux log files to Splunk and each type was tagged different.  E.g. /var/log/messages was tagged linux.messages and /var/log/secure was tagged linux.secure.  I expected to see these messages have different sourcetypes in Splunk because I had not configured the sourcetype in my plugin config.  However, all messages showed up with the same tag 'linux.messages'.

I changed the variable event_sourcetype to be locally scoped. I.e. removed the `@` and things started to work properly.

**Comment by wimnat** [comment]
Created a PR https://github.com/cmeerbeek/fluent-plugin-splunkhec/pull/9

**Comment by cmeerbeek** [comment]
Thanks for the PR! I've merged it.
